main: net.dmg2.RegenBlock.RegenBlock
name: RegenBlock
version: Beta 3.4 Unofficial Fork

permissions:
    regenblock.self:
        description: Allows to use plugin.
        default: op

commands:
   regenblock:
      description: Main command
      permission: regenblock.self
      usage: |
          /regenblock list - Lists player's current selection
          /regenblock blacklist add/remove (id id id ...) - adds/removes supplied block IDs
          /regenblock reload - restores all blocks in queue and reloads the configuration file
          /regenblock region list - lists current regions
          /regenblock region create (name) (re-spawn time) - assigns selection to a region
          /regenblock region remove (name) - removes region from the list
          /regenblock region type (name) (type) - sets region type, 0 for normal, 1 for mine, 2 to regen at intervals, 3 for 1 and 2 combined.
          /regenblock region modify (name) (re-spawn time) - modify existing region
          /regenblock region modify time (name) (re-spawn time) - modify existing region's re-spawn time
          /regenblock region blacklist (name) add/remove (id id id ...) - adds/removes supplied block IDs for region
          /regenblock region feedback (name) (type) - sets feedback type for the region. 0 - none, 1 - on place, 2 - on place/remove
          /regenblock region feedback set (string) - sets string sent to player during region feedback. Use TIME to show re-spawn time.
   rb:
      description: Main command
      permission: regenblock.self
      usage: |
          /regenblock list - Lists player's current selection
          /regenblock blacklist add/remove (id id id ...) - adds/removes supplied block IDs
          /regenblock reload - restores all blocks in queue and reloads the configuration file
          /regenblock select - Starts/stops player's selection mode
          /regenblock region list - lists current regions
          /regenblock region create (name) (re-spawn time) - assigns selection to a region
          /regenblock region remove (name) - removes region from the list
          /regenblock region type (name) (type) - sets region type, 0 for normal, 1 for mine, 2 to regen at intervals, 3 for 1 and 2 combined.
          /regenblock region modify (name) (re-spawn time) - modify existing region
          /regenblock region modify time (name) (re-spawn time) - modify existing region's re-spawn time
          /regenblock region blacklist (name) add/remove (id id id ...) - adds/removes supplied block IDs for region
          /regenblock region feedback (name) (type) - sets feedback type for the region. 0 - none, 1 - on place, 2 - on place/remove
          /regenblock region feedback set (string) - sets string sent to player during region feedback. Use TIME to show re-spawn time.
